#!/usr/bin/env python3
import json, os
D = "/Users/diogo/Desktop/uplift-portal-audit/src/i18n/locales"

def update(code, p, t):
    fp = os.path.join(D, f"{code}.json")
    with open(fp, "r", encoding="utf-8") as f:
        data = json.load(f)
    data["legal"]["privacy"] = p
    data["legal"]["terms"] = t
    with open(fp, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")
    print(f"  {code}")

# DE - German
update("de", {
    "title": "Datenschutzrichtlinie",
    "lastUpdated": "Zuletzt aktualisiert: Januar 2026",
    "s1Title": "1. Einleitung",
    "s1Text": "Uplift (\"wir\", \"unser\" oder \"uns\") verpflichtet sich zum Schutz Ihrer Privatsphäre. Diese Datenschutzrichtlinie erläutert, wie wir Ihre Informationen erfassen, verwenden, offenlegen und schützen, wenn Sie unsere Workforce-Intelligence-Plattform nutzen.",
    "s2Title": "2. Informationen, die wir erfassen",
    "s2aTitle": "2.1 Personenbezogene Daten",
    "s2aText": "Wir können personenbezogene Daten erfassen, die Sie direkt angeben, darunter:",
    "s2aItem1": "Name, E-Mail-Adresse und Telefonnummer",
    "s2aItem2": "Beschäftigungsdetails (Berufsbezeichnung, Abteilung, Arbeitsort)",
    "s2aItem3": "Fähigkeiten und Zertifizierungen",
    "s2aItem4": "Arbeitszeitpräferenzen und Verfügbarkeit",
    "s2aItem5": "Zeit- und Anwesenheitsdaten",
    "s2bTitle": "2.2 Nutzungsdaten",
    "s2bText": "Wir erfassen automatisch bestimmte Informationen, wenn Sie den Dienst nutzen:",
    "s2bItem1": "Geräteinformationen (Browsertyp, Betriebssystem)",
    "s2bItem2": "IP-Adresse und Standortdaten",
    "s2bItem3": "Nutzungsmuster und Feature-Interaktionen",
    "s2bItem4": "Anmeldezeiten und Sitzungsdauer",
    "s3Title": "3. Wie wir Ihre Informationen verwenden",
    "s3Text": "Wir verwenden die gesammelten Informationen, um:",
    "s3Item1": "Den Dienst bereitzustellen und zu warten",
    "s3Item2": "Planungs- und Workforce-Management-Funktionen zu verarbeiten",
    "s3Item3": "Benachrichtigungen über Schichten, Freizeit und Möglichkeiten zu senden",
    "s3Item4": "Analysen und Erkenntnisse für Ihre Organisation zu erstellen",
    "s3Item5": "Unseren Dienst zu verbessern und neue Funktionen zu entwickeln",
    "s3Item6": "Mit Ihnen über Updates und Support zu kommunizieren",
    "s3Item7": "Gesetzliche Verpflichtungen zu erfüllen",
    "s4Title": "4. Datenweitergabe",
    "s4Text": "Wir können Ihre Informationen teilen mit:",
    "s4Item1Label": "Ihrem Arbeitgeber:",
    "s4Item1Text": "Da die Plattform Organisationen zur Verfügung gestellt wird, hat Ihr Arbeitgeber Zugang zu arbeitsbezogenen Daten",
    "s4Item2Label": "Dienstleistern:",
    "s4Item2Text": "Dritte, die uns beim Betrieb des Dienstes unterstützen (z.B. Cloud-Hosting, Zahlungsabwicklung)",
    "s4Item3Label": "Gesetzliche Anforderungen:",
    "s4Item3Text": "Wenn gesetzlich vorgeschrieben oder zum Schutz unserer Rechte",
    "s4NoSell": "Wir verkaufen Ihre personenbezogenen Daten nicht an Dritte.",
    "s5Title": "5. Datensicherheit",
    "s5Text": "Wir implementieren angemessene technische und organisatorische Maßnahmen zum Schutz Ihrer personenbezogenen Daten, darunter:",
    "s5Item1": "Verschlüsselung von Daten bei der Übertragung und im Ruhezustand",
    "s5Item2": "Regelmäßige Sicherheitsbewertungen und Penetrationstests",
    "s5Item3": "Zugriffskontrollen und Authentifizierungsmechanismen",
    "s5Item4": "Mitarbeiterschulungen zum Datenschutz",
    "s6Title": "6. Datenaufbewahrung",
    "s6Text": "Wir bewahren Ihre personenbezogenen Daten so lange auf, wie es für die Bereitstellung des Dienstes und die Erfüllung der in dieser Richtlinie beschriebenen Zwecke erforderlich ist, es sei denn, eine längere Aufbewahrungsfrist ist gesetzlich vorgeschrieben.",
    "s7Title": "7. Ihre Rechte (DSGVO)",
    "s7Text": "Wenn Sie sich im Europäischen Wirtschaftsraum befinden, haben Sie das Recht auf:",
    "s7Item1Label": "Auskunft:",
    "s7Item1Text": "Eine Kopie Ihrer personenbezogenen Daten anfordern",
    "s7Item2Label": "Berichtigung:",
    "s7Item2Text": "Korrektur unrichtiger Daten verlangen",
    "s7Item3Label": "Löschung:",
    "s7Item3Text": "Löschung Ihrer Daten verlangen (\"Recht auf Vergessenwerden\")",
    "s7Item4Label": "Datenübertragbarkeit:",
    "s7Item4Text": "Ihre Daten in einem maschinenlesbaren Format erhalten",
    "s7Item5Label": "Widerspruch:",
    "s7Item5Text": "Bestimmter Verarbeitung Ihrer Daten widersprechen",
    "s7Item6Label": "Einschränkung:",
    "s7Item6Text": "Einschränkung der Verarbeitung verlangen",
    "s7Contact": "Um diese Rechte auszuüben, kontaktieren Sie uns unter privacy@getuplift.io oder nutzen Sie die Self-Service-Optionen in Ihren Kontoeinstellungen.",
    "s8Title": "8. Cookies",
    "s8Text": "Wir verwenden Cookies und ähnliche Tracking-Technologien, um die Aktivität auf unserem Dienst zu verfolgen. Diese werden für Authentifizierung, Einstellungen und Analysen verwendet. Sie können die Cookie-Einstellungen über Ihren Browser steuern.",
    "s9Title": "9. Internationale Übertragungen",
    "s9Text": "Ihre Informationen können in andere Länder als Ihr Wohnsitzland übertragen und dort verarbeitet werden. Wir stellen sicher, dass angemessene Schutzmaßnahmen für solche Übertragungen gemäß den geltenden Datenschutzgesetzen vorhanden sind.",
    "s10Title": "10. Datenschutz für Kinder",
    "s10Text": "Unser Dienst richtet sich nicht an Personen unter 16 Jahren. Wir erfassen nicht wissentlich personenbezogene Daten von Kindern unter 16 Jahren.",
    "s11Title": "11. Änderungen dieser Richtlinie",
    "s11Text": "Wir können diese Datenschutzrichtlinie von Zeit zu Zeit aktualisieren. Wir werden Sie über Änderungen informieren, indem wir die neue Richtlinie auf dieser Seite veröffentlichen und das Datum \"Zuletzt aktualisiert\" aktualisieren.",
    "s12Title": "12. Kontakt",
    "s12Text": "Wenn Sie Fragen zu dieser Datenschutzrichtlinie haben oder Ihre Datenrechte ausüben möchten, kontaktieren Sie uns bitte:",
    "dpoLabel": "Datenschutzbeauftragter:",
    "addressLabel": "Adresse:",
    "address": "London, Vereinigtes Königreich"
}, {
    "title": "Nutzungsbedingungen",
    "lastUpdated": "Zuletzt aktualisiert: Januar 2026",
    "s1Title": "1. Annahme der Bedingungen",
    "s1Text": "Durch den Zugriff auf oder die Nutzung der Workforce-Intelligence-Plattform von Uplift (\"Dienst\") erklären Sie sich mit diesen Nutzungsbedingungen (\"Bedingungen\") einverstanden. Wenn Sie mit einem Teil dieser Bedingungen nicht einverstanden sind, dürfen Sie den Dienst nicht nutzen.",
    "s2Title": "2. Beschreibung des Dienstes",
    "s2Text": "Uplift bietet eine Workforce-Intelligence-SaaS-Plattform, die KI-Planung, Kompetenzerfassung, Karrierepfad-Transparenz und Gamification-Funktionen umfasst, um Organisationen bei der effektiveren Verwaltung ihrer Belegschaft zu unterstützen.",
    "s3Title": "3. Benutzerkonten",
    "s3Text1": "Bei der Erstellung eines Kontos müssen Sie genaue, vollständige und aktuelle Informationen angeben. Ein Verstoß dagegen stellt eine Verletzung dieser Bedingungen dar und kann zur sofortigen Kündigung Ihres Kontos führen.",
    "s3Text2": "Sie sind für den Schutz Ihres Passworts und für alle Aktivitäten unter Ihrem Konto verantwortlich. Sie verpflichten sich, Ihr Passwort keinem Dritten mitzuteilen.",
    "s4Title": "4. Datenschutz",
    "s4Text": "Wir nehmen den Datenschutz ernst. Ihre Nutzung des Dienstes unterliegt auch unserer Datenschutzrichtlinie, die beschreibt, wie wir Ihre personenbezogenen Daten erfassen, verwenden und schützen.",
    "s5Title": "5. Akzeptable Nutzung",
    "s5Text": "Sie verpflichten sich, Folgendes zu unterlassen:",
    "s5Item1": "Den Dienst für rechtswidrige Zwecke zu nutzen",
    "s5Item2": "Unbefugten Zugang zu Teilen des Dienstes zu erlangen",
    "s5Item3": "Den Dienst oder Server zu stören oder zu beeinträchtigen",
    "s5Item4": "Schädlichen Code oder Inhalte hochzuladen",
    "s5Item5": "Kontodaten mit unbefugten Nutzern zu teilen",
    "s6Title": "6. Geistiges Eigentum",
    "s6Text": "Der Dienst und seine Originalinhalte, Funktionen und Funktionalität sind Eigentum von Uplift und durch internationale Urheberrechts-, Marken- und andere Gesetze zum Schutz geistigen Eigentums geschützt.",
    "s7Title": "7. Abonnement und Zahlung",
    "s7Text": "Einige Teile des Dienstes werden auf Abonnementbasis abgerechnet. Die Abrechnung erfolgt im Voraus auf wiederkehrender Basis, monatlich oder jährlich, je nach Ihrem Abonnementplan.",
    "s8Title": "8. Kündigung",
    "s8Text": "Wir können Ihr Konto jederzeit ohne Vorankündigung oder Haftung kündigen oder sperren, einschließlich bei Verstoß gegen diese Bedingungen. Nach der Kündigung erlischt Ihr Recht zur Nutzung des Dienstes sofort.",
    "s9Title": "9. Haftungsbeschränkung",
    "s9Text": "In keinem Fall haften Uplift, seine Direktoren, Mitarbeiter, Partner oder Lieferanten für indirekte, zufällige, besondere, Folge- oder Strafschäden, einschließlich Verlust von Gewinnen, Daten oder Firmenwert.",
    "s10Title": "10. Änderungen der Bedingungen",
    "s10Text": "Wir behalten uns das Recht vor, diese Bedingungen jederzeit zu ändern. Wir werden Sie über wesentliche Änderungen informieren, indem wir die neuen Bedingungen auf dieser Seite veröffentlichen und das Datum \"Zuletzt aktualisiert\" aktualisieren.",
    "s11Title": "11. Kontakt",
    "s11Text": "Wenn Sie Fragen zu diesen Bedingungen haben, kontaktieren Sie uns bitte:",
    "emailLabel": "E-Mail:",
    "addressLabel": "Adresse:",
    "address": "London, Vereinigtes Königreich"
})

# FR - French
update("fr", {
    "title": "Politique de confidentialité",
    "lastUpdated": "Dernière mise à jour : janvier 2026",
    "s1Title": "1. Introduction",
    "s1Text": "Uplift (\"nous\", \"notre\" ou \"nos\") s'engage à protéger votre vie privée. Cette politique de confidentialité explique comment nous collectons, utilisons, divulguons et protégeons vos informations lorsque vous utilisez notre plateforme d'intelligence des effectifs.",
    "s2Title": "2. Informations que nous collectons",
    "s2aTitle": "2.1 Informations personnelles",
    "s2aText": "Nous pouvons collecter des informations personnelles que vous fournissez directement, notamment :",
    "s2aItem1": "Nom, adresse e-mail et numéro de téléphone",
    "s2aItem2": "Détails de l'emploi (intitulé du poste, département, lieu de travail)",
    "s2aItem3": "Compétences et certifications",
    "s2aItem4": "Préférences d'horaires de travail et disponibilité",
    "s2aItem5": "Données de temps et de présence",
    "s2bTitle": "2.2 Données d'utilisation",
    "s2bText": "Nous collectons automatiquement certaines informations lorsque vous utilisez le Service :",
    "s2bItem1": "Informations sur l'appareil (type de navigateur, système d'exploitation)",
    "s2bItem2": "Adresse IP et données de localisation",
    "s2bItem3": "Habitudes d'utilisation et interactions avec les fonctionnalités",
    "s2bItem4": "Heures de connexion et durée de session",
    "s3Title": "3. Comment nous utilisons vos informations",
    "s3Text": "Nous utilisons les informations collectées pour :",
    "s3Item1": "Fournir et maintenir le Service",
    "s3Item2": "Traiter les fonctions de planification et de gestion des effectifs",
    "s3Item3": "Envoyer des notifications sur les quarts, les congés et les opportunités",
    "s3Item4": "Générer des analyses et des informations pour votre organisation",
    "s3Item5": "Améliorer notre Service et développer de nouvelles fonctionnalités",
    "s3Item6": "Communiquer avec vous concernant les mises à jour et le support",
    "s3Item7": "Respecter les obligations légales",
    "s4Title": "4. Partage des données",
    "s4Text": "Nous pouvons partager vos informations avec :",
    "s4Item1Label": "Votre employeur :",
    "s4Item1Text": "La plateforme étant fournie aux organisations, votre employeur a accès aux données liées au travail",
    "s4Item2Label": "Prestataires de services :",
    "s4Item2Text": "Des tiers qui nous aident à exploiter le Service (par ex., hébergement cloud, traitement des paiements)",
    "s4Item3Label": "Exigences légales :",
    "s4Item3Text": "Lorsque la loi l'exige ou pour protéger nos droits",
    "s4NoSell": "Nous ne vendons pas vos informations personnelles à des tiers.",
    "s5Title": "5. Sécurité des données",
    "s5Text": "Nous mettons en œuvre des mesures techniques et organisationnelles appropriées pour protéger vos informations personnelles, notamment :",
    "s5Item1": "Chiffrement des données en transit et au repos",
    "s5Item2": "Évaluations de sécurité régulières et tests de pénétration",
    "s5Item3": "Contrôles d'accès et mécanismes d'authentification",
    "s5Item4": "Formation des employés sur la protection des données",
    "s6Title": "6. Conservation des données",
    "s6Text": "Nous conservons vos informations personnelles aussi longtemps que nécessaire pour fournir le Service et remplir les objectifs décrits dans cette politique, sauf si une période de conservation plus longue est requise par la loi.",
    "s7Title": "7. Vos droits (RGPD)",
    "s7Text": "Si vous êtes dans l'Espace économique européen, vous avez le droit de :",
    "s7Item1Label": "Accès :",
    "s7Item1Text": "Demander une copie de vos données personnelles",
    "s7Item2Label": "Rectification :",
    "s7Item2Text": "Demander la correction de données inexactes",
    "s7Item3Label": "Effacement :",
    "s7Item3Text": "Demander la suppression de vos données (\"droit à l'oubli\")",
    "s7Item4Label": "Portabilité :",
    "s7Item4Text": "Recevoir vos données dans un format lisible par machine",
    "s7Item5Label": "Opposition :",
    "s7Item5Text": "Vous opposer à certains traitements de vos données",
    "s7Item6Label": "Limitation :",
    "s7Item6Text": "Demander la limitation du traitement",
    "s7Contact": "Pour exercer ces droits, contactez-nous à privacy@getuplift.io ou utilisez les options en libre-service dans les paramètres de votre compte.",
    "s8Title": "8. Cookies",
    "s8Text": "Nous utilisons des cookies et des technologies de suivi similaires pour suivre l'activité sur notre Service. Ils sont utilisés pour l'authentification, les préférences et les analyses. Vous pouvez contrôler les paramètres des cookies via votre navigateur.",
    "s9Title": "9. Transferts internationaux",
    "s9Text": "Vos informations peuvent être transférées et traitées dans des pays autres que votre pays de résidence. Nous veillons à ce que des garanties appropriées soient en place pour ces transferts conformément aux lois applicables sur la protection des données.",
    "s10Title": "10. Confidentialité des enfants",
    "s10Text": "Notre Service ne s'adresse pas aux personnes de moins de 16 ans. Nous ne collectons pas sciemment d'informations personnelles auprès d'enfants de moins de 16 ans.",
    "s11Title": "11. Modifications de cette politique",
    "s11Text": "Nous pouvons mettre à jour cette politique de confidentialité de temps à autre. Nous vous informerons de tout changement en publiant la nouvelle politique sur cette page et en mettant à jour la date de « Dernière mise à jour ».",
    "s12Title": "12. Nous contacter",
    "s12Text": "Si vous avez des questions sur cette politique de confidentialité ou souhaitez exercer vos droits, veuillez nous contacter :",
    "dpoLabel": "Délégué à la protection des données :",
    "addressLabel": "Adresse :",
    "address": "Londres, Royaume-Uni"
}, {
    "title": "Conditions d'utilisation",
    "lastUpdated": "Dernière mise à jour : janvier 2026",
    "s1Title": "1. Acceptation des conditions",
    "s1Text": "En accédant ou en utilisant la plateforme d'intelligence des effectifs d'Uplift (\"Service\"), vous acceptez d'être lié par ces Conditions d'utilisation (\"Conditions\"). Si vous n'êtes pas d'accord avec une partie de ces conditions, vous ne pouvez pas accéder au Service.",
    "s2Title": "2. Description du Service",
    "s2Text": "Uplift fournit une plateforme SaaS d'intelligence des effectifs comprenant la planification par IA, le suivi des compétences, la visibilité des parcours de carrière et des fonctionnalités de gamification pour aider les organisations à gérer plus efficacement leurs effectifs.",
    "s3Title": "3. Comptes utilisateurs",
    "s3Text1": "Lors de la création d'un compte, vous devez fournir des informations exactes, complètes et à jour. Le non-respect de cette obligation constitue une violation de ces Conditions et peut entraîner la résiliation immédiate de votre compte.",
    "s3Text2": "Vous êtes responsable de la protection de votre mot de passe et de toutes les activités effectuées sous votre compte. Vous acceptez de ne pas divulguer votre mot de passe à des tiers.",
    "s4Title": "4. Protection des données",
    "s4Text": "Nous prenons la protection des données au sérieux. Votre utilisation du Service est également régie par notre Politique de confidentialité.",
    "s5Title": "5. Utilisation acceptable",
    "s5Text": "Vous acceptez de ne pas :",
    "s5Item1": "Utiliser le Service à des fins illégales",
    "s5Item2": "Tenter d'obtenir un accès non autorisé à toute partie du Service",
    "s5Item3": "Interférer avec ou perturber le Service ou les serveurs",
    "s5Item4": "Télécharger du code ou du contenu malveillant",
    "s5Item5": "Partager les identifiants de compte avec des utilisateurs non autorisés",
    "s6Title": "6. Propriété intellectuelle",
    "s6Text": "Le Service et son contenu original, ses fonctionnalités et sa fonctionnalité sont la propriété d'Uplift et sont protégés par les lois internationales sur le droit d'auteur, les marques et autres lois sur la propriété intellectuelle.",
    "s7Title": "7. Abonnement et paiement",
    "s7Text": "Certaines parties du Service sont facturées sur la base d'un abonnement. Vous serez facturé à l'avance sur une base récurrente, mensuelle ou annuelle, selon votre plan d'abonnement.",
    "s8Title": "8. Résiliation",
    "s8Text": "Nous pouvons résilier ou suspendre votre compte immédiatement, sans préavis ni responsabilité, pour toute raison, y compris en cas de violation de ces Conditions.",
    "s9Title": "9. Limitation de responsabilité",
    "s9Text": "En aucun cas Uplift, ses directeurs, employés, partenaires ou fournisseurs ne seront responsables de dommages indirects, accessoires, spéciaux, consécutifs ou punitifs.",
    "s10Title": "10. Modifications des conditions",
    "s10Text": "Nous nous réservons le droit de modifier ces Conditions à tout moment. Nous vous informerons de tout changement important en publiant les nouvelles Conditions sur cette page.",
    "s11Title": "11. Nous contacter",
    "s11Text": "Si vous avez des questions sur ces Conditions, veuillez nous contacter :",
    "emailLabel": "E-mail :",
    "addressLabel": "Adresse :",
    "address": "Londres, Royaume-Uni"
})

# ES - Spanish
update("es", {
    "title": "Política de privacidad",
    "lastUpdated": "Última actualización: enero 2026",
    "s1Title": "1. Introducción",
    "s1Text": "Uplift (\"nosotros\", \"nuestro\" o \"nos\") se compromete a proteger su privacidad. Esta Política de Privacidad explica cómo recopilamos, usamos, divulgamos y protegemos su información cuando utiliza nuestra plataforma de inteligencia de fuerza laboral.",
    "s2Title": "2. Información que recopilamos",
    "s2aTitle": "2.1 Información personal",
    "s2aText": "Podemos recopilar información personal que proporcione directamente, incluyendo:",
    "s2aItem1": "Nombre, dirección de correo electrónico y número de teléfono",
    "s2aItem2": "Detalles de empleo (cargo, departamento, ubicación de trabajo)",
    "s2aItem3": "Habilidades y certificaciones",
    "s2aItem4": "Preferencias de horario de trabajo y disponibilidad",
    "s2aItem5": "Datos de tiempo y asistencia",
    "s2bTitle": "2.2 Datos de uso",
    "s2bText": "Recopilamos automáticamente cierta información cuando utiliza el Servicio:",
    "s2bItem1": "Información del dispositivo (tipo de navegador, sistema operativo)",
    "s2bItem2": "Dirección IP y datos de ubicación",
    "s2bItem3": "Patrones de uso e interacciones con funciones",
    "s2bItem4": "Tiempos de inicio de sesión y duración de la sesión",
    "s3Title": "3. Cómo usamos su información",
    "s3Text": "Usamos la información recopilada para:",
    "s3Item1": "Proporcionar y mantener el Servicio",
    "s3Item2": "Procesar funciones de programación y gestión de fuerza laboral",
    "s3Item3": "Enviar notificaciones sobre turnos, tiempo libre y oportunidades",
    "s3Item4": "Generar análisis e información para su organización",
    "s3Item5": "Mejorar nuestro Servicio y desarrollar nuevas funciones",
    "s3Item6": "Comunicarnos con usted sobre actualizaciones y soporte",
    "s3Item7": "Cumplir con obligaciones legales",
    "s4Title": "4. Compartir datos",
    "s4Text": "Podemos compartir su información con:",
    "s4Item1Label": "Su empleador:",
    "s4Item1Text": "Como la plataforma se proporciona a organizaciones, su empleador tiene acceso a datos relacionados con el trabajo",
    "s4Item2Label": "Proveedores de servicios:",
    "s4Item2Text": "Terceros que nos ayudan a operar el Servicio (por ej., alojamiento en la nube, procesamiento de pagos)",
    "s4Item3Label": "Requisitos legales:",
    "s4Item3Text": "Cuando lo exija la ley o para proteger nuestros derechos",
    "s4NoSell": "No vendemos su información personal a terceros.",
    "s5Title": "5. Seguridad de los datos",
    "s5Text": "Implementamos medidas técnicas y organizativas apropiadas para proteger su información personal, incluyendo:",
    "s5Item1": "Cifrado de datos en tránsito y en reposo",
    "s5Item2": "Evaluaciones de seguridad regulares y pruebas de penetración",
    "s5Item3": "Controles de acceso y mecanismos de autenticación",
    "s5Item4": "Capacitación de empleados en protección de datos",
    "s6Title": "6. Retención de datos",
    "s6Text": "Conservamos su información personal durante el tiempo necesario para proporcionar el Servicio y cumplir los propósitos descritos en esta política, a menos que la ley requiera un período de retención más largo.",
    "s7Title": "7. Sus derechos (RGPD)",
    "s7Text": "Si se encuentra en el Espacio Económico Europeo, tiene derecho a:",
    "s7Item1Label": "Acceso:",
    "s7Item1Text": "Solicitar una copia de sus datos personales",
    "s7Item2Label": "Rectificación:",
    "s7Item2Text": "Solicitar la corrección de datos inexactos",
    "s7Item3Label": "Supresión:",
    "s7Item3Text": "Solicitar la eliminación de sus datos (\"derecho al olvido\")",
    "s7Item4Label": "Portabilidad:",
    "s7Item4Text": "Recibir sus datos en un formato legible por máquina",
    "s7Item5Label": "Oposición:",
    "s7Item5Text": "Oponerse a ciertos procesamientos de sus datos",
    "s7Item6Label": "Limitación:",
    "s7Item6Text": "Solicitar la limitación del procesamiento",
    "s7Contact": "Para ejercer estos derechos, contáctenos en privacy@getuplift.io o utilice las opciones de autoservicio en la configuración de su cuenta.",
    "s8Title": "8. Cookies",
    "s8Text": "Utilizamos cookies y tecnologías de seguimiento similares para rastrear la actividad en nuestro Servicio. Se utilizan para autenticación, preferencias y análisis. Puede controlar la configuración de cookies a través de su navegador.",
    "s9Title": "9. Transferencias internacionales",
    "s9Text": "Su información puede ser transferida y procesada en países distintos al de su residencia. Garantizamos que existan las salvaguardas apropiadas para dichas transferencias de conformidad con las leyes de protección de datos aplicables.",
    "s10Title": "10. Privacidad de los niños",
    "s10Text": "Nuestro Servicio no está dirigido a personas menores de 16 años. No recopilamos conscientemente información personal de niños menores de 16 años.",
    "s11Title": "11. Cambios en esta política",
    "s11Text": "Podemos actualizar esta Política de Privacidad periódicamente. Le notificaremos cualquier cambio publicando la nueva política en esta página y actualizando la fecha de \"Última actualización\".",
    "s12Title": "12. Contáctenos",
    "s12Text": "Si tiene preguntas sobre esta Política de Privacidad o desea ejercer sus derechos, contáctenos:",
    "dpoLabel": "Delegado de protección de datos:",
    "addressLabel": "Dirección:",
    "address": "Londres, Reino Unido"
}, {
    "title": "Términos de servicio",
    "lastUpdated": "Última actualización: enero 2026",
    "s1Title": "1. Aceptación de los términos",
    "s1Text": "Al acceder o utilizar la plataforma de inteligencia de fuerza laboral de Uplift (\"Servicio\"), acepta estar sujeto a estos Términos de Servicio (\"Términos\"). Si no está de acuerdo con alguna parte, no puede acceder al Servicio.",
    "s2Title": "2. Descripción del Servicio",
    "s2Text": "Uplift proporciona una plataforma SaaS de inteligencia de fuerza laboral que incluye programación con IA, seguimiento de habilidades, visibilidad de trayectorias profesionales y funciones de gamificación para ayudar a las organizaciones a gestionar su fuerza laboral de manera más efectiva.",
    "s3Title": "3. Cuentas de usuario",
    "s3Text1": "Al crear una cuenta, debe proporcionar información precisa, completa y actual. No hacerlo constituye una violación de estos Términos y puede resultar en la terminación inmediata de su cuenta.",
    "s3Text2": "Usted es responsable de proteger su contraseña y de todas las actividades que ocurran bajo su cuenta. Acepta no revelar su contraseña a terceros.",
    "s4Title": "4. Protección de datos",
    "s4Text": "Tomamos la protección de datos en serio. Su uso del Servicio también se rige por nuestra Política de Privacidad.",
    "s5Title": "5. Uso aceptable",
    "s5Text": "Acepta no:",
    "s5Item1": "Usar el Servicio para fines ilegales",
    "s5Item2": "Intentar obtener acceso no autorizado a cualquier parte del Servicio",
    "s5Item3": "Interferir con o interrumpir el Servicio o los servidores",
    "s5Item4": "Cargar código o contenido malicioso",
    "s5Item5": "Compartir credenciales de cuenta con usuarios no autorizados",
    "s6Title": "6. Propiedad intelectual",
    "s6Text": "El Servicio y su contenido original, características y funcionalidad son propiedad de Uplift y están protegidos por leyes internacionales de propiedad intelectual.",
    "s7Title": "7. Suscripción y pago",
    "s7Text": "Algunas partes del Servicio se facturan por suscripción. Se le facturará por adelantado de forma recurrente, mensual o anualmente, según su plan.",
    "s8Title": "8. Terminación",
    "s8Text": "Podemos terminar o suspender su cuenta inmediatamente, sin previo aviso ni responsabilidad, por cualquier razón, incluyendo el incumplimiento de estos Términos.",
    "s9Title": "9. Limitación de responsabilidad",
    "s9Text": "En ningún caso Uplift, sus directores, empleados, socios o proveedores serán responsables de daños indirectos, incidentales, especiales, consecuentes o punitivos.",
    "s10Title": "10. Cambios en los términos",
    "s10Text": "Nos reservamos el derecho de modificar estos Términos en cualquier momento. Le notificaremos cualquier cambio material publicando los nuevos Términos en esta página.",
    "s11Title": "11. Contáctenos",
    "s11Text": "Si tiene preguntas sobre estos Términos, contáctenos:",
    "emailLabel": "Correo electrónico:",
    "addressLabel": "Dirección:",
    "address": "Londres, Reino Unido"
})

print("Batch 1 done (de, fr, es)")
